export const TableData = [
    {
        id: "101",
        image: "https://m.media-amazon.com/images/I/81QpkIctqPL._AC_SX679_.jpg",
        name: "Acer 21.5 Inch Full HD (1920 x 1080) IPS Ultra-Thin Zero Frame Computer Monitor (HDMI & VGA Port), SB220Q bi",
        price: "500$",
        orderdate: "2021-09-01",
        review: "Great monitor with vibrant colors and sharp display. The slim design adds a modern touch to my workspace.",
        rating: 4,
        quantity: 10
    },
    {
        id: "102",
        image: "https://m.media-amazon.com/images/I/819hAP4xoGS._AC_SX679_.jpg",
        name: "SAMSUNG Galaxy Tab A7 Lite 8.7 32GB WiFi Android Tablet, Compact, Slim Design, Kid Friendly, Sturdy Metal Frame, Long Lasting Battery, US Version, 2021, Gray",
        price: "450$",
        orderdate: "2021-09-10",
        review: null,
        rating: null,
        quantity: "Out of stock"
    },
    {
        id: "103",
        image: "https://m.media-amazon.com/images/I/41pAi7odesS._AC_SX679_.jpg",
        name: "Echo Frames (2nd Gen) | Smart audio sunglasses with Alexa | Classic Black with new polarized blue mirror sunglass lenses",
        price: "300$",
        orderdate: "2021-10-01",
        review: null,
        rating: null,
    },
    {
        id: "104",
        image: "https://m.media-amazon.com/images/I/715s8YMjHjL._AC_SX679_.jpg",
        name: "UPSYTIO Vintage Scrapbook Kit, Journaling Scrapbooking Supplies with A6 Grid Notebook, Aesthetic Paper, Stickers, Washi Tape for DIY Craft (346pcs)",
        price: "200$",
        orderdate: "2021-10-01",
        review: "The scrapbook kit exceeded my expectations! The materials are of excellent quality, and I love the variety of designs available.",
        rating: 5,
    },
    {
        id: "105",
        image: "https://m.media-amazon.com/images/I/81fn7j-PFBL._AC_UX679_.jpg",
        name: "CASIO watch G-SHOCK Mad master world six stations corresponding Solar radio GWG-1000-1A3JF Men's",
        price: "147$",
        orderdate: "2022-09-01",
        review: "The watch looks stylish and feels durable. However, the price is a bit steep for the features it offers.",
        rating: 3,
    },
    {
        id: "106",
        image: "https://m.media-amazon.com/images/I/617sGSjmC1L._AC_SX679_.jpg",
        name: "GoPro HERO11 Black - Waterproof Action Camera with 5.3K60 Ultra HD Video, 27MP Photos, 1/1.9 Image Sensor, Live Streaming, Webcam, Stabilization",
        price: "160$",
        orderdate: "2022-04-23",
        review: "The GoPro HERO11 Black is an incredible action camera! It captures stunning videos and photos, and the stabilization feature is a game-changer.",
        rating: 5,
    },
    {
        id: "107",
        image: "https://m.media-amazon.com/images/I/71Yt-laN1IL._AC_SX679_.jpg",
        name: "Samsonite Centric 2 Hardside Expandable Luggage with Spinners, True Navy, 3-Piece Set (20/24/28)",
        price: "232.99$",
        orderdate: "2019-09-11",
        review: "The Samsonite Centric 2 luggage set is both stylish and durable. It provides ample space for all my travel essentials, and the spinner wheels make maneuvering a breeze.",
        rating: 4,
    },
    {
        id: "108",
        image: "https://m.media-amazon.com/images/I/61IG46p-yHL._SX522_.jpg",
        name: "DualShock 4 Wireless Controller for PlayStation 4 - Jet Black",
        price: "89.99$",
        orderdate: "2022-01-01",
        review: null,
        rating: null,
    },
    {
        id: "109",
        image: "https://m.media-amazon.com/images/I/71tB4Ibgo4L._AC_SX679_.jpg",
        name: "The DEWALT 20V MAX combo kit is a powerhouse! The tools are incredibly powerful and reliable. The only downside is that they can be a bit heavy to handle for extended periods.",
        price: "400$",
        orderdate: "2022-09-01",
        review: "Powerful tools, but a bit heavy.",
        rating: 4,
    },
    {
        id: "110",
        image: "https://m.media-amazon.com/images/I/911ujeCkGfL._AC_SX679_.jpg",
        name: "SAMSUNG Electronics 870 EVO 2TB 2.5 Inch SATA III Internal SSD (MZ-77E2T0B/AM))",
        price: "180$",
        orderdate: "2023-02-01",
        review: null,
        rating: null,
    },
    {
        id: "111",
        image: "https://m.media-amazon.com/images/I/81QpkIctqPL._AC_SX679_.jpg",
        name: "Acer 21.5 Inch Full HD (1920 x 1080) IPS Ultra-Thin Zero Frame Computer Monitor (HDMI & VGA Port), SB220Q bi",
        price: "500$",
        orderdate: "2023-03-03",
        review: null,
        rating: null,
    },
];
